services:
  denoise_api:
    image: angeluz07/denoise-api:0.0.1
    build:
      context: .
    container_name: denoise_api
    ports:
      - "7860:7860"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/app/src:z
      - ./.data:/app/.data:z
    command: ["gradio", "src/main.py"]
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 1.0G
        reservations:
          cpus: "1"
          memory: 0.5G